name: Cypress Tests

on:
  push:
    branches: [main]
  schedule:
    - cron: "0 8 * * 3"

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Replace URL so build works
        run: |
          sed -i "s@REPLACE_SECTION_URL@https://freiburg.esn-germany.de@g" src/app/app.component.ts

      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          browser: firefox
          record: true
          start: yarn start
          wait-on: "http://[::1]:4200"
          config-file: cypress.config.ts
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
